### ISSUE TITLE
Multiple ignore files and paths

### ISSUE THREAD

**Issue by ClemensLinnhoff** [articulate/actions-markdownlint#8]
I am trying to add one file and one directory to the ignore input. I tried, separation with a space, with a comma and putting the input in paranthesis as well as brackets. Nothing worked. The parenthesis and the brackets were rejected and with space or comma separation, only the first entry is ignored.

[This](https://github.com/openMSL/.github/blob/markdownlinter/.github/workflows/markdown.yml) is my workflow file.

**Comment by mloberg** [comment]
I looked into supporting multiple files with ignore, but due to how the underlying tool works and how we have this set up right now, that's unfortunately not possible.

As an alternative we recommend using `.markdownlintignore` as documented [here](https://github.com/igorshubovych/markdownlint-cli#ignoring-files).
